### ISSUE TITLE
ETA not working

### ISSUE THREAD

**Issue by hwy893747147** [gautamchauhan5227/Google-Map#1]
When I try to run your code on my local, I replaced with my own API key, I got the maps showing and everything, but when I click on the button "Go", it says "I/flutter (31139): RangeError (index): Invalid value: Valid value range is empty: 0" 

How do I fix this to get the ETA showing?

Thank you very much.

**Comment by gautamchauhan5227** [comment]
Your google API  key start a property of direction it's api service is
paid. If you start this service after this error show than send a ss.
